// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: serialization.proto

package sstable

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bloomfilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BitSet        []bool                 `protobuf:"varint,1,rep,packed,name=bitSet,proto3" json:"bitSet,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bloomfilter) Reset() {
	*x = Bloomfilter{}
	mi := &file_serialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bloomfilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bloomfilter) ProtoMessage() {}

func (x *Bloomfilter) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bloomfilter.ProtoReflect.Descriptor instead.
func (*Bloomfilter) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *Bloomfilter) GetBitSet() []bool {
	if x != nil {
		return x.BitSet
	}
	return nil
}

func (x *Bloomfilter) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type IndexEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	mi := &file_serialization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{1}
}

func (x *IndexEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IndexEntry) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IndexEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_serialization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{2}
}

func (x *Index) GetEntries() []*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_serialization_proto protoreflect.FileDescriptor

const file_serialization_proto_rawDesc = "" +
	"\n" +
	"\x13serialization.proto\"9\n" +
	"\vBloomfilter\x12\x16\n" +
	"\x06bitSet\x18\x01 \x03(\bR\x06bitSet\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"6\n" +
	"\n" +
	"IndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\".\n" +
	"\x05Index\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.IndexEntryR\aentriesB\fZ\n" +
	"./;sstableb\x06proto3"

var (
	file_serialization_proto_rawDescOnce sync.Once
	file_serialization_proto_rawDescData []byte
)

func file_serialization_proto_rawDescGZIP() []byte {
	file_serialization_proto_rawDescOnce.Do(func() {
		file_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)))
	})
	return file_serialization_proto_rawDescData
}

var file_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_serialization_proto_goTypes = []any{
	(*Bloomfilter)(nil), // 0: Bloomfilter
	(*IndexEntry)(nil),  // 1: IndexEntry
	(*Index)(nil),       // 2: Index
}
var file_serialization_proto_depIdxs = []int32{
	1, // 0: Index.entries:type_name -> IndexEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serialization_proto_init() }
func file_serialization_proto_init() {
	if File_serialization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialization_proto_goTypes,
		DependencyIndexes: file_serialization_proto_depIdxs,
		MessageInfos:      file_serialization_proto_msgTypes,
	}.Build()
	File_serialization_proto = out.File
	file_serialization_proto_goTypes = nil
	file_serialization_proto_depIdxs = nil
}
